name = 'mcp-test-ui'
main = "src/worker.ts"
compatibility_date = "2025-05-26"
workers_dev = false

# Upload built Vite assets
[assets]
directory = "dist"
binding = "ASSETS"

[vars]
# Set via GitHub secret in CI. Fallback here for local testing only.
BACKEND_URL = "https://dynamic-mcp-server-6k5kig7o4a-ey.a.run.app"

[build]
# Build just the client and its shared workspace before deploying
command = "bash -lc 'cd .. && npm ci && cd shared && npm run build && cd ../client && npm run build'"
cwd = "."
watch_dir = ["../shared/src", "./src"]

routes = [
  { pattern = "mcp-test.dev/*", zone_name = "mcp-test.dev" }
]

