services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.prod
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LLM_PROVIDER: ${LLM_PROVIDER}
    depends_on:
      - db
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.prod
      args:
        - VITE_API_URL=${VUE_API_URL}
    environment:
      - VITE_API_URL=${VUE_API_URL}
    depends_on:
      - server
    ports:
      - "80:80"

volumes:
  db-data:
