services:
  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main server application
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    working_dir: /app/server
    volumes:
      # Mount entire workspace for development
      - .:/app
      # Preserve node_modules to avoid overwriting
      - /app/node_modules
      - /app/server/node_modules
      - /app/client/node_modules
      - /app/shared/node_modules
    command: sh -c "npx prisma generate --schema=../prisma/schema.prisma && npm run dev"

  # Separate MCP servers as independent services
  mcp-memory:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    working_dir: /app/server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    environment:
      - MCP_SERVER=memory
    command: sh -c "npx prisma generate --schema=../prisma/schema.prisma && npm run build:mcp-servers && node dist/mcp-servers/memory-server.js"

  mcp-api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3002:3002"
    working_dir: /app/server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    environment:
      - MCP_SERVER=api
    command: sh -c "npx prisma generate --schema=../prisma/schema.prisma && npm run build:mcp-servers && node dist/mcp-servers/dynamic-mcp-api-server.js"

  # Frontend client
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - VITE_API_URL=${VUE_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "5173:5173"
    working_dir: /app/client
    volumes:
      # Mount entire workspace for development
      - .:/app
      # Preserve node_modules to avoid overwriting
      - /app/node_modules
      - /app/client/node_modules
      - /app/shared/node_modules

volumes:
  db-data:
