steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE', '-f', 'server/Dockerfile.gcp', '.']
  - id: push
    name: gcr.io/cloud-builders/docker
    args: ['push', '$_IMAGE']
images:
  - '$_IMAGE'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
