name: Deploy client to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'client/**'
      - 'shared/**'
      - 'packages/typescript-config/**'
      - '.github/workflows/cloudflare-client.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    env:
      NODE_VERSION: '20'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Wrangler
        run: npm i -g wrangler@latest

      - name: Install deps (monorepo)
        run: npm ci

      - name: Build shared + client
        run: |
          npm run build:shared
          npm run build:client

      - name: Publish to Cloudflare
        working-directory: client
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          BACKEND_URL: ${{ secrets.CLIENT_BACKEND_URL }}
        run: |
          # Inject runtime secret variable for Worker
          wrangler secret put BACKEND_URL --non-interactive --text "$BACKEND_URL"
          wrangler deploy


